
#===============================================================================================================#
# Here you can customize what items toaster can cook.
# if you want to add a new item simply create a friendly name as the title
# then add the Item: "" with its appropriate BUKKIT item  name which you can get from here:
#           https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# then add the price which is how much the player will be charged for cooking ONE of this item.
# then set the Exp amount which the player will be given per item cooked, if you want to use levels
# simpy set it as Exp: 3.0L instead of Exp: 3.0 
# and finally set the item type which it will be cooked into, just follow this template and you will be fine!
# FancyFood:
#   Item: "GRASS_BLOCK"
#   Price: 12.57
#   Exp: 2.3
#   Result: "GOLD_BLOCK"
#================================================================================================================#

Cookables:
  
  Chicken:
    Item: "CHICKEN"
    Price: 5.0
    Exp: 3.5
    Result: "COOKED_CHICKEN"
  
  Mutton:
    Item: "MUTTON"
    Price: 5.0
    Exp: 3.5
    Result: "COOKED_MUTTON"
  
  Beef:
    Item: "BEEF"
    Price: 5.0
    Exp: 4.5
    Result: "COOKED_BEEF"
  
  Rabbit:
    Item: "RABBIT"
    Price: 5.0
    Exp: 3.6
    Result: "COOKED_RABBIT"
  
  Cod:
    Item: "COD"
    Price: 4.0
    Exp: 2.5
    Result: "COOKED_COD"
  
  Salmon:
    Item: "SALMON"
    Price: 4.5
    Exp: 3.0
    Result: "COOKED_SALMON"
  
  Potato:
    Item: "POTATO"
    Price: 6.0
    Exp: 2.5
    Result: "BAKED_POTATO"
    
  Pufferfish:
    Item: "PUFFERFISH"
    Price: 8.0
    Exp: 1.0L
    Result: "SPONGE"
    
# Exact same rules mentioned above apply to the smelting section!
# remember, you can add as many items as you want.
# And as long as you follow the template (defined above) nothing will break!
    
Smeltables:
  
  IronOre:
    Item: "IRON_ORE"
    Price: 6.0
    Exp: 12.0
    Result: "IRON_INGOT"
    
  GoldOre:
    Item: "GOLD_ORE"
    Price: 7.5
    Exp: 15.0
    Result: "GOLD_INGOT"
    
  LapisOre:
    Item: "LAPIS_ORE"
    Price: 8.0
    Exp: 22.0
    Result: "LAPIS_LAZULI"
    
  RedstoneOre:
    Item: "REDSTONE_ORE"
    Price: 7.0
    Exp: 20.0
    Result: "REDSTONE"
    
  DiamondOre:
    Item: "DIAMOND_ORE"
    Price: 12.0
    Exp: 26.0
    Result: "DIAMOND"
    
  EmeraldOre:
    Item: "EMERALD_ORE"
    Price: 18.0
    Exp: 28.0
    Result: "EMERALD"
    
  NetherQuartzOre:
    Item: "NETHER_QUARTZ_ORE"
    Price: 20.0
    Exp: 32.0
    Result: "QUARTZ"
    
  Obsidian:
    Item: "OBSIDIAN"
    Price: 35.0
    Exp: 5.0L
    Result: "COAL_BLOCK"
  
  
  